# Simple workflow for deploying static content to GitHub Pages
name: Validate csv content for deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pull-requests: read


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install git+https://github.com/olbys/open-science-catalog-builder@stac-structure --no-cache-dir
      - name: Convert csv to data
        run: |
          osc convert ./csv/Variables.csv ./csv/Themes.csv ./csv/"EO Missions".csv ./csv/Projects.csv ./csv/Products.csv -o data/
      - name: Build static catalog
        run: |
          osc build data/ -o dist/ \
            --root-href "https://olbys.github.io/open-science-catalog-metadata/"
      - name: Copying Catalog client
        run: |
          cp -r client/* dist/
          chmod 755 -R dist
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done



